//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt1HD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int Item_ID { get; set; }
        public string Item_type { get; set; }
        public string Item_brand { get; set; }
        public string Item_model { get; set; }
        public string Additional_comments { get; set; }
    }
}
