//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt1HD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int Review_ID { get; set; }
        public int Item_ID { get; set; }
        public string Advantages { get; set; }
        public string Defects { get; set; }
        public string Review_summary { get; set; }
        public string Rating { get; set; }
        public string Reviewer { get; set; }
        public Nullable<System.DateTime> Review_date { get; set; }
        public Nullable<bool> Product_recommend { get; set; }
        public Nullable<int> Votes_up { get; set; }
        public Nullable<int> Votes_down { get; set; }
        public Nullable<int> Review_CeneoID { get; set; }
        public string Review { get; set; }
    }
}
